In [ ]:
#importando librerías
import pandas as pd
import requests
import numpy as np
import openpyxl
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#mostrar sin límite de columnas ni filas
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [ ]:
#Conectarse a la API

#url de la API
api_url='https://api.yelp.com/v3/businesses/search'

#estos datos corresponden a una cuenta de usuario creada previamente
clientid='GWOCZh9-BmZxtdsAjr7Gug'
apikey='FHVvXoNmTXIl9DuxYis7AV5uLPujm9MLwrhgs5NgvCfaOxd3V6mxt6dQU8eEqYJiGxe816XATx7ufWjbMWqbV-2Uku1jxBJv8BGRC74NroLPl27PDQqs0tDixit-YHYx'
headers={'Authorization':'Bearer %s'%apikey}

In [ ]:
#Elegimos la ciudad "chicago"
ciudad = "Chicago" # Se puede elegir cualquier ciudad del dataset entregado

In [5]:
# De esta manera se consulta el API de Yelp para obtener información sobre restaurantes en la ciudad especificada
params={'term':'restaurants','location': ciudad,'limit':50}
response=requests.get(api_url,params=params,headers=headers)
data=response.json()
data

{'businesses': [{'id': 'qjnpkS8yZO8xcyEIy5OU9A',
   'alias': 'girl-and-the-goat-chicago',
   'name': 'Girl & The Goat',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/ya6gjD4BPlxe7AKMj_5WsA/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/girl-and-the-goat-chicago?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 10667,
   'categories': [{'alias': 'newamerican', 'title': 'New American'},
    {'alias': 'bars', 'title': 'Bars'},
    {'alias': 'bakeries', 'title': 'Bakeries'}],
   'rating': 4.4,
   'coordinates': {'latitude': 41.88419277030351,
    'longitude': -87.64794613195826},
   'transactions': ['delivery'],
   'price': '$$$',
   'location': {'address1': '809 W Randolph',
    'address2': '',
    'address3': '',
    'city': 'Chicago',
    'zip_code': '60607',
    'country': 'US',
    'state': 'IL',
    'display_address': ['809 W Randolph', 'Chicago, IL 60607']},
   'phone': '+13124926262',
   'display_phone': '(312) 492-6262',
   'distance': 3401.2386759023707},
  {'id': 'boE4Ahsssqic7o5wQLI04w',
   'alias': 'the-purple-pig-chicago',
   'name': 'The Purple Pig',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/8993TKAeJ2rhDST6tuqh4A/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/the-purple-pig-chicago?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 8984,
   'categories': [{'alias': 'tapasmallplates', 'title': 'Tapas/Small Plates'},
    {'alias': 'mediterranean', 'title': 'Mediterranean'},
    {'alias': 'newamerican', 'title': 'New American'}],
   'rating': 4.3,
   'coordinates': {'latitude': 41.890694, 'longitude': -87.624782},
   'transactions': ['pickup', 'delivery'],
   'price': '$$$',
   'location': {'address1': '444 N Michigan Ave',
    'address2': None,
    'address3': '',
    'city': 'Chicago',
    'zip_code': '60611',
    'country': 'US',
    'state': 'IL',
    'display_address': ['444 N Michigan Ave', 'Chicago, IL 60611']},
   'phone': '+13124641744',
   'display_phone': '(312) 464-1744',
   'distance': 4672.658118380336},
  {'id': 'riT822EnU7y_5eCuJsd9sA',
   'alias': 'cindys-rooftop-chicago',
   'name': "Cindy's Rooftop",
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/XLdHyZLsRMogjR4GNWCe-A/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/cindys-rooftop-chicago?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 2812,
   'categories': [{'alias': 'newamerican', 'title': 'New American'},
    {'alias': 'seafood', 'title': 'Seafood'},
    {'alias': 'breakfast_brunch', 'title': 'Breakfast & Brunch'}],
   'rating': 4.1,
   'coordinates': {'latitude': 41.8816894031196,
    'longitude': -87.6250061730162},
   'transactions': ['restaurant_reservation', 'delivery'],
   'price': '$$$',
   'location': {'address1': '12 S Michigan Ave',
    'address2': '',
    'address3': '',
    'city': 'Chicago',
    'zip_code': '60603',
    'country': 'US',
    'state': 'IL',
    'display_address': ['12 S Michigan Ave', 'Chicago, IL 60603']},
   'phone': '+13127923502',
   'display_phone': '(312) 792-3502',
   'distance': 5091.190048420359},
  {'id': 'PZe0q_153VHUnaR-8dOTJg',
   'alias': 'the-dearborn-chicago-2',
   'name': 'The Dearborn',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/eSXeGiq2bRUjy7KOER4jeg/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/the-dearborn-chicago-2?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 2739,
   'categories': [{'alias': 'newamerican', 'title': 'New American'},
    {'alias': 'breakfast_brunch', 'title': 'Breakfast & Brunch'},
    {'alias': 'beer_and_wine', 'title': 'Beer, Wine & Spirits'}],
   'rating': 4.4,
   'coordinates': {'latitude': 41.8842528, 'longitude': -87.6293151},
   'transactions': ['delivery', 'pickup'],
   'price': '$$',
   'location': {'address1': '145 N Dearborn St',
    'address2': '',
    'address3': None,
    'city': 'Chicago',
    'zip_code': '60602',
    'country': 'US',
    'state': 'IL',
    'display_address': ['145 N Dearborn St', 'Chicago, IL 60602']},
   'phone': '+13123841242',
   'display_phone': '(312) 384-1242',
   'distance': 4637.0435326330025},
  {'id': 'cgIuo3geaxw1Sfhbqm5qTA',
   'alias': 'alla-vita-chicago-4',
   'name': 'Alla Vita',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/X4XMxKMr4FfFdplvdP1BjA/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/alla-vita-chicago-4?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 813,
   'categories': [{'alias': 'italian', 'title': 'Italian'}],
   'rating': 4.4,
   'coordinates': {'latitude': 41.88468, 'longitude': -87.642322},
   'transactions': ['delivery', 'pickup'],
   'price': '$$$',
   'location': {'address1': '564 W Randolph St',
    'address2': None,
    'address3': None,
    'city': 'Chicago',
    'zip_code': '60661',
    'country': 'US',
    'state': 'IL',
    'display_address': ['564 W Randolph St', 'Chicago, IL 60661']},
   'phone': '+13126670104',
   'display_phone': '(312) 667-0104',
   'distance': 3714.5750911319506},
  {'id': 'GZsrGq6H8CQ4YlGtE_Bm0Q',
   'alias': 'ciccio-mio-chicago-2',
   'name': 'Ciccio Mio',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/eFIrEMfnmALCGrR1gSJKLQ/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/ciccio-mio-chicago-2?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 632,
   'categories': [{'alias': 'italian', 'title': 'Italian'}],
   'rating': 4.7,
   'coordinates': {'latitude': 41.8892649696079,
    'longitude': -87.63521477367367},
   'transactions': ['delivery'],
   'price': '$$$',
   'location': {'address1': '226 W Kinzie',
    'address2': '',
    'address3': None,
    'city': 'Chicago',
    'zip_code': '60654',
    'country': 'US',
    'state': 'IL',
    'display_address': ['226 W Kinzie', 'Chicago, IL 60654']},
   'phone': '+13127963316',
   'display_phone': '(312) 796-3316',
   'distance': 3943.404234393604},
  {'id': 'VPJk-SEWSWS_nGoQvM-COw',
   'alias': 'penumbra-chicago',
   'name': 'Penumbra',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/94lq8yKQGs0QFecHmxQVtg/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/penumbra-chicago?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 1029,
   'categories': [{'alias': 'wine_bars', 'title': 'Wine Bars'},
    {'alias': 'seafood', 'title': 'Seafood'},
    {'alias': 'steak', 'title': 'Steakhouses'}],
   'rating': 4.8,
   'coordinates': {'latitude': 41.924459, 'longitude': -87.710898},
   'transactions': ['restaurant_reservation', 'delivery'],
   'price': '$$$',
   'location': {'address1': '3309 W Fullerton Ave',
    'address2': None,
    'address3': '',
    'city': 'Chicago',
    'zip_code': '60647',
    'country': 'US',
    'state': 'IL',
    'display_address': ['3309 W Fullerton Ave', 'Chicago, IL 60647']},
   'phone': '+17737722343',
   'display_phone': '(773) 772-2343',
   'distance': 3480.7928840306017},
  {'id': 'gzhkdb6YoiFm5s3vriG1AA',
   'alias': 'gretel-chicago',
   'name': 'Gretel',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/Q0Um9fewaLX9nr8QWbZtrA/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/gretel-chicago?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 456,
   'categories': [{'alias': 'cocktailbars', 'title': 'Cocktail Bars'},
    {'alias': 'newamerican', 'title': 'New American'},
    {'alias': 'speakeasies', 'title': 'Speakeasies'}],
   'rating': 4.5,
   'coordinates': {'latitude': 41.917275, 'longitude': -87.698577},
   'transactions': ['delivery', 'pickup'],
   'price': '$$',
   'location': {'address1': '2833 W Armitage Ave',
    'address2': '',
    'address3': None,
    'city': 'Chicago',
    'zip_code': '60647',
    'country': 'US',
    'state': 'IL',
    'display_address': ['2833 W Armitage Ave', 'Chicago, IL 60647']},
   'phone': '+17737703427',
   'display_phone': '(773) 770-3427',
   'distance': 2181.370354175089},
  {'id': 'tuJraaFffIS_JNK_4ZqGTA',
   'alias': 'ema-chicago-6',
   'name': 'Ema',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/EA7Wq13hk7PKgZ4xl5hUJQ/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/ema-chicago-6?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 1919,
   'categories': [{'alias': 'mediterranean', 'title': 'Mediterranean'},
    {'alias': 'tapasmallplates', 'title': 'Tapas/Small Plates'},
    {'alias': 'salad', 'title': 'Salad'}],
   'rating': 4.3,
   'coordinates': {'latitude': 41.890964390624795,
    'longitude': -87.63090253497006},
   'transactions': ['delivery', 'pickup'],
   'price': '$$',
   'location': {'address1': '74 W Illinois St',
    'address2': None,
    'address3': None,
    'city': 'Chicago',
    'zip_code': '60654',
    'country': 'US',
    'state': 'IL',
    'display_address': ['74 W Illinois St', 'Chicago, IL 60654']},
   'phone': '+13125275586',
   'display_phone': '(312) 527-5586',
   'distance': 4189.6572301334145},
  {'id': '1BHgaf25FpVSOXFpZF0pYw',
   'alias': 'trivoli-tavern-chicago',
   'name': 'Trivoli Tavern',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/kMNBfN-NjwMPEeAQwo0Qrg/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/trivoli-tavern-chicago?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 961,
   'categories': [{'alias': 'tradamerican', 'title': 'American'}],
   'rating': 4.5,
   'coordinates': {'latitude': 41.8837221888722,
    'longitude': -87.64903867652058},
   'transactions': ['delivery'],
   'price': '$$',
   'location': {'address1': '114 N Green St',
    'address2': None,
    'address3': '',
    'city': 'Chicago',
    'zip_code': '60607',
    'country': 'US',
    'state': 'IL',
    'display_address': ['114 N Green St', 'Chicago, IL 60607']},
   'phone': '+13123662646',
   'display_phone': '(312) 366-2646',
   'distance': 3373.2131317248645},
  {'id': 'okaqMJEoHfHblpKz9Q-CMA',
   'alias': 'the-perch-chicago',
   'name': 'The Perch',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/ffuLlvFIl7P8F_pkyFqBCA/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/the-perch-chicago?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 600,
   'categories': [{'alias': 'breweries', 'title': 'Breweries'},
    {'alias': 'newamerican', 'title': 'New American'}],
   'rating': 4.4,
   'coordinates': {'latitude': 41.90348, 'longitude': -87.676221},
   'transactions': ['delivery', 'pickup'],
   'price': '$$',
   'location': {'address1': '1932 W Division',
    'address2': None,
    'address3': '',
    'city': 'Chicago',
    'zip_code': '60622',
    'country': 'US',
    'state': 'IL',
    'display_address': ['1932 W Division', 'Chicago, IL 60622']},
   'phone': '+17734862739',
   'display_phone': '(773) 486-2739',
   'distance': 239.42719598525488},
  {'id': '8N3GMu-AhVvJMzQifkNemg',
   'alias': 'crying-tiger-chicago',
   'name': 'Crying Tiger',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/J-JrcFCrNuleqIV-ELHDHQ/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/crying-tiger-chicago?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 173,
   'categories': [{'alias': 'thai', 'title': 'Thai'}],
   'rating': 4.2,
   'coordinates': {'latitude': 41.88990307515616, 'longitude': -87.6298989},
   'transactions': [],
   'location': {'address1': '51 W Hubbard St',
    'address2': '',
    'address3': None,
    'city': 'Chicago',
    'zip_code': '60654',
    'country': 'US',
    'state': 'IL',
    'display_address': ['51 W Hubbard St', 'Chicago, IL 60654']},
   'phone': '+13127360183',
   'display_phone': '(312) 736-0183',
   'distance': 4312.01949347675},
  {'id': 'apyIymDFbUK7u-Y3V5kmkA',
   'alias': 'bavettes-bar-and-boeuf-chicago',
   'name': "Bavette's Bar & Boeuf",
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/mhw9kdjyIBe1A0vGIKlI9Q/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/bavettes-bar-and-boeuf-chicago?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 3501,
   'categories': [{'alias': 'steak', 'title': 'Steakhouses'},
    {'alias': 'seafood', 'title': 'Seafood'},
    {'alias': 'bars', 'title': 'Bars'}],
   'rating': 4.5,
   'coordinates': {'latitude': 41.889295011779424,
    'longitude': -87.63489302317039},
   'transactions': ['delivery'],
   'price': '$$$$',
   'location': {'address1': '218 W Kinzie',
    'address2': '',
    'address3': '',
    'city': 'Chicago',
    'zip_code': '60654',
    'country': 'US',
    'state': 'IL',
    'display_address': ['218 W Kinzie', 'Chicago, IL 60654']},
   'phone': '+13126248154',
   'display_phone': '(312) 624-8154',
   'distance': 3965.6928058367052},
  {'id': 'Z8K7SVH-B7ZVAVD9aFIK8w',
   'alias': 'bar-mar-by-josé-andrés-chicago-2',
   'name': 'Bar Mar',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/ZfSYel2Muyh1hAqf6eRYZg/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/bar-mar-by-jos%C3%A9-andr%C3%A9s-chicago-2?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 625,
   'categories': [{'alias': 'seafood', 'title': 'Seafood'},
    {'alias': 'cocktailbars', 'title': 'Cocktail Bars'}],
   'rating': 4.3,
   'coordinates': {'latitude': 41.883835, 'longitude': -87.6372458},
   'transactions': [],
   'price': '$$$',
   'location': {'address1': '120 N Wacker Dr',
    'address2': None,
    'address3': '',
    'city': 'Chicago',
    'zip_code': '60606',
    'country': 'US',
    'state': 'IL',
    'display_address': ['120 N Wacker Dr', 'Chicago, IL 60606']},
   'phone': '+13128206602',
   'display_phone': '(312) 820-6602',
   'distance': 4102.904355999825},
  {'id': 'xoi7Cw7FoknAx5p880RtWQ',
   'alias': 'au-cheval-chicago',
   'name': 'Au Cheval',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/vKY9dRK2GM6eQDP-Cxg_tw/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/au-cheval-chicago?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 9492,
   'categories': [{'alias': 'bars', 'title': 'Bars'},
    {'alias': 'burgers', 'title': 'Burgers'},
    {'alias': 'tradamerican', 'title': 'American'}],
   'rating': 4.4,
   'coordinates': {'latitude': 41.88466, 'longitude': -87.647668},
   'transactions': ['pickup', 'delivery'],
   'price': '$$',
   'location': {'address1': '800 W Randolph St',
    'address2': '',
    'address3': '',
    'city': 'Chicago',
    'zip_code': '60607',
    'country': 'US',
    'state': 'IL',
    'display_address': ['800 W Randolph St', 'Chicago, IL 60607']},
   'phone': '+13129294580',
   'display_phone': '(312) 929-4580',
   'distance': 3382.5619870115283},
  {'id': '1Q7RL7Hc63wKa2A9ec3zXw',
   'alias': 'il-porcellino-chicago',
   'name': 'Il Porcellino',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/zrAfaD2GsQLkel9UZAjZdg/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/il-porcellino-chicago?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 1755,
   'categories': [{'alias': 'italian', 'title': 'Italian'},
    {'alias': 'bars', 'title': 'Bars'},
    {'alias': 'salad', 'title': 'Salad'}],
   'rating': 4.4,
   'coordinates': {'latitude': 41.88996108569464,
    'longitude': -87.63029733223148},
   'transactions': ['delivery', 'pickup'],
   'price': '$$',
   'location': {'address1': '59 W Hubbard St',
    'address2': '',
    'address3': '',
    'city': 'Chicago',
    'zip_code': '60654',
    'country': 'US',
    'state': 'IL',
    'display_address': ['59 W Hubbard St', 'Chicago, IL 60654']},
   'phone': '+13125950800',
   'display_phone': '(312) 595-0800',
   'distance': 4279.188564018985},
  {'id': '9nUrDQ_REhU6sgcgXFAyfA',
   'alias': 'aba-chicago-2',
   'name': 'Aba',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/CeQacWWhLEiFBYw2piRozA/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/aba-chicago-2?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 1951,
   'categories': [{'alias': 'mediterranean', 'title': 'Mediterranean'},
    {'alias': 'tapasmallplates', 'title': 'Tapas/Small Plates'}],
   'rating': 4.4,
   'coordinates': {'latitude': 41.8869441, 'longitude': -87.6487949},
   'transactions': ['delivery', 'pickup'],
   'price': '$$$',
   'location': {'address1': '302 N Green St',
    'address2': 'Fl 3',
    'address3': None,
    'city': 'Chicago',
    'zip_code': '60607',
    'country': 'US',
    'state': 'IL',
    'display_address': ['302 N Green St', 'Fl 3', 'Chicago, IL 60607']},
   'phone': '+17736451400',
   'display_phone': '(773) 645-1400',
   'distance': 3120.1445058575764},
  {'id': 'o0DaPvRb4IWH7hUWVCnoGw',
   'alias': 'monteverde-chicago',
   'name': 'Monteverde',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/A0UG6ziTe9jmMbDC4O8fVg/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/monteverde-chicago?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 1523,
   'categories': [{'alias': 'italian', 'title': 'Italian'},
    {'alias': 'desserts', 'title': 'Desserts'},
    {'alias': 'wine_bars', 'title': 'Wine Bars'}],
   'rating': 4.5,
   'coordinates': {'latitude': 41.88191, 'longitude': -87.65302},
   'transactions': ['delivery'],
   'price': '$$$',
   'location': {'address1': '1020 W Madison St',
    'address2': '',
    'address3': '',
    'city': 'Chicago',
    'zip_code': '60607',
    'country': 'US',
    'state': 'IL',
    'display_address': ['1020 W Madison St', 'Chicago, IL 60607']},
   'phone': '+13128883041',
   'display_phone': '(312) 888-3041',
   'distance': 3313.005604959832},
  {'id': '0ucCbCekcn5XdzvRXnHl2w',
   'alias': 'desert-hawk-chicago',
   'name': 'Desert Hawk',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/Wvt0tJNb-HbxRnBQ7iUUPQ/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/desert-hawk-chicago?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 45,
   'categories': [{'alias': 'tradamerican', 'title': 'American'},
    {'alias': 'bars', 'title': 'Bars'}],
   'rating': 4.6,
   'coordinates': {'latitude': 41.90288666670101,
    'longitude': -87.67917606979607},
   'transactions': [],
   'location': {'address1': '2049 W Division St',
    'address2': '',
    'address3': None,
    'city': 'Chicago',
    'zip_code': '60622',
    'country': 'US',
    'state': 'IL',
    'display_address': ['2049 W Division St', 'Chicago, IL 60622']},

In [6]:
#Veamos los keys del diccionario recibido
data.keys()

dict_keys(['businesses', 'total', 'region'])

In [21]:
#El primer elemento del diccionario indica el total de restaurants existentes en la API
print('En total la base de datos registra %d restaurants'%data['total'])

En total la base de datos registra 7800 restaurants

In [ ]:
data['businesses']

[{'id': 'qjnpkS8yZO8xcyEIy5OU9A',
  'alias': 'girl-and-the-goat-chicago',
  'name': 'Girl & The Goat',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/ya6gjD4BPlxe7AKMj_5WsA/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/girl-and-the-goat-chicago?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 10667,
  'categories': [{'alias': 'newamerican', 'title': 'New American'},
   {'alias': 'bars', 'title': 'Bars'},
   {'alias': 'bakeries', 'title': 'Bakeries'}],
  'rating': 4.4,
  'coordinates': {'latitude': 41.88419277030351,
   'longitude': -87.64794613195826},
  'transactions': ['delivery'],
  'price': '$$$',
  'location': {'address1': '809 W Randolph',
   'address2': '',
   'address3': '',
   'city': 'Chicago',
   'zip_code': '60607',
   'country': 'US',
   'state': 'IL',
   'display_address': ['809 W Randolph', 'Chicago, IL 60607']},
  'phone': '+13124926262',
  'display_phone': '(312) 492-6262',
  'distance': 3401.2386759023707},
 {'id': 'boE4Ahsssqic7o5wQLI04w',
  'alias': 'the-purple-pig-chicago',
  'name': 'The Purple Pig',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/8993TKAeJ2rhDST6tuqh4A/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/the-purple-pig-chicago?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 8984,
  'categories': [{'alias': 'tapasmallplates', 'title': 'Tapas/Small Plates'},
   {'alias': 'mediterranean', 'title': 'Mediterranean'},
   {'alias': 'newamerican', 'title': 'New American'}],
  'rating': 4.3,
  'coordinates': {'latitude': 41.890694, 'longitude': -87.624782},
  'transactions': ['pickup', 'delivery'],
  'price': '$$$',
  'location': {'address1': '444 N Michigan Ave',
   'address2': None,
   'address3': '',
   'city': 'Chicago',
   'zip_code': '60611',
   'country': 'US',
   'state': 'IL',
   'display_address': ['444 N Michigan Ave', 'Chicago, IL 60611']},
  'phone': '+13124641744',
  'display_phone': '(312) 464-1744',
  'distance': 4672.658118380336},
 {'id': 'riT822EnU7y_5eCuJsd9sA',
  'alias': 'cindys-rooftop-chicago',
  'name': "Cindy's Rooftop",
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/XLdHyZLsRMogjR4GNWCe-A/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/cindys-rooftop-chicago?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 2812,
  'categories': [{'alias': 'newamerican', 'title': 'New American'},
   {'alias': 'seafood', 'title': 'Seafood'},
   {'alias': 'breakfast_brunch', 'title': 'Breakfast & Brunch'}],
  'rating': 4.1,
  'coordinates': {'latitude': 41.8816894031196,
   'longitude': -87.6250061730162},
  'transactions': ['restaurant_reservation', 'delivery'],
  'price': '$$$',
  'location': {'address1': '12 S Michigan Ave',
   'address2': '',
   'address3': '',
   'city': 'Chicago',
   'zip_code': '60603',
   'country': 'US',
   'state': 'IL',
   'display_address': ['12 S Michigan Ave', 'Chicago, IL 60603']},
  'phone': '+13127923502',
  'display_phone': '(312) 792-3502',
  'distance': 5091.190048420359},
 {'id': 'PZe0q_153VHUnaR-8dOTJg',
  'alias': 'the-dearborn-chicago-2',
  'name': 'The Dearborn',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/eSXeGiq2bRUjy7KOER4jeg/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/the-dearborn-chicago-2?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 2739,
  'categories': [{'alias': 'newamerican', 'title': 'New American'},
   {'alias': 'breakfast_brunch', 'title': 'Breakfast & Brunch'},
   {'alias': 'beer_and_wine', 'title': 'Beer, Wine & Spirits'}],
  'rating': 4.4,
  'coordinates': {'latitude': 41.8842528, 'longitude': -87.6293151},
  'transactions': ['delivery', 'pickup'],
  'price': '$$',
  'location': {'address1': '145 N Dearborn St',
   'address2': '',
   'address3': None,
   'city': 'Chicago',
   'zip_code': '60602',
   'country': 'US',
   'state': 'IL',
   'display_address': ['145 N Dearborn St', 'Chicago, IL 60602']},
  'phone': '+13123841242',
  'display_phone': '(312) 384-1242',
  'distance': 4637.0435326330025},
 {'id': 'cgIuo3geaxw1Sfhbqm5qTA',
  'alias': 'alla-vita-chicago-4',
  'name': 'Alla Vita',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/X4XMxKMr4FfFdplvdP1BjA/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/alla-vita-chicago-4?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 813,
  'categories': [{'alias': 'italian', 'title': 'Italian'}],
  'rating': 4.4,
  'coordinates': {'latitude': 41.88468, 'longitude': -87.642322},
  'transactions': ['delivery', 'pickup'],
  'price': '$$$',
  'location': {'address1': '564 W Randolph St',
   'address2': None,
   'address3': None,
   'city': 'Chicago',
   'zip_code': '60661',
   'country': 'US',
   'state': 'IL',
   'display_address': ['564 W Randolph St', 'Chicago, IL 60661']},
  'phone': '+13126670104',
  'display_phone': '(312) 667-0104',
  'distance': 3714.5750911319506},
 {'id': 'GZsrGq6H8CQ4YlGtE_Bm0Q',
  'alias': 'ciccio-mio-chicago-2',
  'name': 'Ciccio Mio',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/eFIrEMfnmALCGrR1gSJKLQ/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/ciccio-mio-chicago-2?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 632,
  'categories': [{'alias': 'italian', 'title': 'Italian'}],
  'rating': 4.7,
  'coordinates': {'latitude': 41.8892649696079,
   'longitude': -87.63521477367367},
  'transactions': ['delivery'],
  'price': '$$$',
  'location': {'address1': '226 W Kinzie',
   'address2': '',
   'address3': None,
   'city': 'Chicago',
   'zip_code': '60654',
   'country': 'US',
   'state': 'IL',
   'display_address': ['226 W Kinzie', 'Chicago, IL 60654']},
  'phone': '+13127963316',
  'display_phone': '(312) 796-3316',
  'distance': 3943.404234393604},
 {'id': 'VPJk-SEWSWS_nGoQvM-COw',
  'alias': 'penumbra-chicago',
  'name': 'Penumbra',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/94lq8yKQGs0QFecHmxQVtg/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/penumbra-chicago?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 1029,
  'categories': [{'alias': 'wine_bars', 'title': 'Wine Bars'},
   {'alias': 'seafood', 'title': 'Seafood'},
   {'alias': 'steak', 'title': 'Steakhouses'}],
  'rating': 4.8,
  'coordinates': {'latitude': 41.924459, 'longitude': -87.710898},
  'transactions': ['restaurant_reservation', 'delivery'],
  'price': '$$$',
  'location': {'address1': '3309 W Fullerton Ave',
   'address2': None,
   'address3': '',
   'city': 'Chicago',
   'zip_code': '60647',
   'country': 'US',
   'state': 'IL',
   'display_address': ['3309 W Fullerton Ave', 'Chicago, IL 60647']},
  'phone': '+17737722343',
  'display_phone': '(773) 772-2343',
  'distance': 3480.7928840306017},
 {'id': 'gzhkdb6YoiFm5s3vriG1AA',
  'alias': 'gretel-chicago',
  'name': 'Gretel',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/Q0Um9fewaLX9nr8QWbZtrA/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/gretel-chicago?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 456,
  'categories': [{'alias': 'cocktailbars', 'title': 'Cocktail Bars'},
   {'alias': 'newamerican', 'title': 'New American'},
   {'alias': 'speakeasies', 'title': 'Speakeasies'}],
  'rating': 4.5,
  'coordinates': {'latitude': 41.917275, 'longitude': -87.698577},
  'transactions': ['delivery', 'pickup'],
  'price': '$$',
  'location': {'address1': '2833 W Armitage Ave',
   'address2': '',
   'address3': None,
   'city': 'Chicago',
   'zip_code': '60647',
   'country': 'US',
   'state': 'IL',
   'display_address': ['2833 W Armitage Ave', 'Chicago, IL 60647']},
  'phone': '+17737703427',
  'display_phone': '(773) 770-3427',
  'distance': 2181.370354175089},
 {'id': 'tuJraaFffIS_JNK_4ZqGTA',
  'alias': 'ema-chicago-6',
  'name': 'Ema',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/EA7Wq13hk7PKgZ4xl5hUJQ/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/ema-chicago-6?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 1919,
  'categories': [{'alias': 'mediterranean', 'title': 'Mediterranean'},
   {'alias': 'tapasmallplates', 'title': 'Tapas/Small Plates'},
   {'alias': 'salad', 'title': 'Salad'}],
  'rating': 4.3,
  'coordinates': {'latitude': 41.890964390624795,
   'longitude': -87.63090253497006},
  'transactions': ['delivery', 'pickup'],
  'price': '$$',
  'location': {'address1': '74 W Illinois St',
   'address2': None,
   'address3': None,
   'city': 'Chicago',
   'zip_code': '60654',
   'country': 'US',
   'state': 'IL',
   'display_address': ['74 W Illinois St', 'Chicago, IL 60654']},
  'phone': '+13125275586',
  'display_phone': '(312) 527-5586',
  'distance': 4189.6572301334145},
 {'id': '1BHgaf25FpVSOXFpZF0pYw',
  'alias': 'trivoli-tavern-chicago',
  'name': 'Trivoli Tavern',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/kMNBfN-NjwMPEeAQwo0Qrg/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/trivoli-tavern-chicago?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 961,
  'categories': [{'alias': 'tradamerican', 'title': 'American'}],
  'rating': 4.5,
  'coordinates': {'latitude': 41.8837221888722,
   'longitude': -87.64903867652058},
  'transactions': ['delivery'],
  'price': '$$',
  'location': {'address1': '114 N Green St',
   'address2': None,
   'address3': '',
   'city': 'Chicago',
   'zip_code': '60607',
   'country': 'US',
   'state': 'IL',
   'display_address': ['114 N Green St', 'Chicago, IL 60607']},
  'phone': '+13123662646',
  'display_phone': '(312) 366-2646',
  'distance': 3373.2131317248645},
 {'id': 'okaqMJEoHfHblpKz9Q-CMA',
  'alias': 'the-perch-chicago',
  'name': 'The Perch',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/ffuLlvFIl7P8F_pkyFqBCA/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/the-perch-chicago?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 600,
  'categories': [{'alias': 'breweries', 'title': 'Breweries'},
   {'alias': 'newamerican', 'title': 'New American'}],
  'rating': 4.4,
  'coordinates': {'latitude': 41.90348, 'longitude': -87.676221},
  'transactions': ['delivery', 'pickup'],
  'price': '$$',
  'location': {'address1': '1932 W Division',
   'address2': None,
   'address3': '',
   'city': 'Chicago',
   'zip_code': '60622',
   'country': 'US',
   'state': 'IL',
   'display_address': ['1932 W Division', 'Chicago, IL 60622']},
  'phone': '+17734862739',
  'display_phone': '(773) 486-2739',
  'distance': 239.42719598525488},
 {'id': '8N3GMu-AhVvJMzQifkNemg',
  'alias': 'crying-tiger-chicago',
  'name': 'Crying Tiger',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/J-JrcFCrNuleqIV-ELHDHQ/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/crying-tiger-chicago?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 173,
  'categories': [{'alias': 'thai', 'title': 'Thai'}],
  'rating': 4.2,
  'coordinates': {'latitude': 41.88990307515616, 'longitude': -87.6298989},
  'transactions': [],
  'location': {'address1': '51 W Hubbard St',
   'address2': '',
   'address3': None,
   'city': 'Chicago',
   'zip_code': '60654',
   'country': 'US',
   'state': 'IL',
   'display_address': ['51 W Hubbard St', 'Chicago, IL 60654']},
  'phone': '+13127360183',
  'display_phone': '(312) 736-0183',
  'distance': 4312.01949347675},
 {'id': 'apyIymDFbUK7u-Y3V5kmkA',
  'alias': 'bavettes-bar-and-boeuf-chicago',
  'name': "Bavette's Bar & Boeuf",
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/mhw9kdjyIBe1A0vGIKlI9Q/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/bavettes-bar-and-boeuf-chicago?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 3501,
  'categories': [{'alias': 'steak', 'title': 'Steakhouses'},
   {'alias': 'seafood', 'title': 'Seafood'},
   {'alias': 'bars', 'title': 'Bars'}],
  'rating': 4.5,
  'coordinates': {'latitude': 41.889295011779424,
   'longitude': -87.63489302317039},
  'transactions': ['delivery'],
  'price': '$$$$',
  'location': {'address1': '218 W Kinzie',
   'address2': '',
   'address3': '',
   'city': 'Chicago',
   'zip_code': '60654',
   'country': 'US',
   'state': 'IL',
   'display_address': ['218 W Kinzie', 'Chicago, IL 60654']},
  'phone': '+13126248154',
  'display_phone': '(312) 624-8154',
  'distance': 3965.6928058367052},
 {'id': 'Z8K7SVH-B7ZVAVD9aFIK8w',
  'alias': 'bar-mar-by-josé-andrés-chicago-2',
  'name': 'Bar Mar',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/ZfSYel2Muyh1hAqf6eRYZg/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/bar-mar-by-jos%C3%A9-andr%C3%A9s-chicago-2?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 625,
  'categories': [{'alias': 'seafood', 'title': 'Seafood'},
   {'alias': 'cocktailbars', 'title': 'Cocktail Bars'}],
  'rating': 4.3,
  'coordinates': {'latitude': 41.883835, 'longitude': -87.6372458},
  'transactions': [],
  'price': '$$$',
  'location': {'address1': '120 N Wacker Dr',
   'address2': None,
   'address3': '',
   'city': 'Chicago',
   'zip_code': '60606',
   'country': 'US',
   'state': 'IL',
   'display_address': ['120 N Wacker Dr', 'Chicago, IL 60606']},
  'phone': '+13128206602',
  'display_phone': '(312) 820-6602',
  'distance': 4102.904355999825},
 {'id': 'xoi7Cw7FoknAx5p880RtWQ',
  'alias': 'au-cheval-chicago',
  'name': 'Au Cheval',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/vKY9dRK2GM6eQDP-Cxg_tw/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/au-cheval-chicago?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 9492,
  'categories': [{'alias': 'bars', 'title': 'Bars'},
   {'alias': 'burgers', 'title': 'Burgers'},
   {'alias': 'tradamerican', 'title': 'American'}],
  'rating': 4.4,
  'coordinates': {'latitude': 41.88466, 'longitude': -87.647668},
  'transactions': ['pickup', 'delivery'],
  'price': '$$',
  'location': {'address1': '800 W Randolph St',
   'address2': '',
   'address3': '',
   'city': 'Chicago',
   'zip_code': '60607',
   'country': 'US',
   'state': 'IL',
   'display_address': ['800 W Randolph St', 'Chicago, IL 60607']},
  'phone': '+13129294580',
  'display_phone': '(312) 929-4580',
  'distance': 3382.5619870115283},
 {'id': '1Q7RL7Hc63wKa2A9ec3zXw',
  'alias': 'il-porcellino-chicago',
  'name': 'Il Porcellino',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/zrAfaD2GsQLkel9UZAjZdg/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/il-porcellino-chicago?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 1755,
  'categories': [{'alias': 'italian', 'title': 'Italian'},
   {'alias': 'bars', 'title': 'Bars'},
   {'alias': 'salad', 'title': 'Salad'}],
  'rating': 4.4,
  'coordinates': {'latitude': 41.88996108569464,
   'longitude': -87.63029733223148},
  'transactions': ['delivery', 'pickup'],
  'price': '$$',
  'location': {'address1': '59 W Hubbard St',
   'address2': '',
   'address3': '',
   'city': 'Chicago',
   'zip_code': '60654',
   'country': 'US',
   'state': 'IL',
   'display_address': ['59 W Hubbard St', 'Chicago, IL 60654']},
  'phone': '+13125950800',
  'display_phone': '(312) 595-0800',
  'distance': 4279.188564018985},
 {'id': '9nUrDQ_REhU6sgcgXFAyfA',
  'alias': 'aba-chicago-2',
  'name': 'Aba',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/CeQacWWhLEiFBYw2piRozA/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/aba-chicago-2?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 1951,
  'categories': [{'alias': 'mediterranean', 'title': 'Mediterranean'},
   {'alias': 'tapasmallplates', 'title': 'Tapas/Small Plates'}],
  'rating': 4.4,
  'coordinates': {'latitude': 41.8869441, 'longitude': -87.6487949},
  'transactions': ['delivery', 'pickup'],
  'price': '$$$',
  'location': {'address1': '302 N Green St',
   'address2': 'Fl 3',
   'address3': None,
   'city': 'Chicago',
   'zip_code': '60607',
   'country': 'US',
   'state': 'IL',
   'display_address': ['302 N Green St', 'Fl 3', 'Chicago, IL 60607']},
  'phone': '+17736451400',
  'display_phone': '(773) 645-1400',
  'distance': 3120.1445058575764},
 {'id': 'o0DaPvRb4IWH7hUWVCnoGw',
  'alias': 'monteverde-chicago',
  'name': 'Monteverde',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/A0UG6ziTe9jmMbDC4O8fVg/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/monteverde-chicago?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 1523,
  'categories': [{'alias': 'italian', 'title': 'Italian'},
   {'alias': 'desserts', 'title': 'Desserts'},
   {'alias': 'wine_bars', 'title': 'Wine Bars'}],
  'rating': 4.5,
  'coordinates': {'latitude': 41.88191, 'longitude': -87.65302},
  'transactions': ['delivery'],
  'price': '$$$',
  'location': {'address1': '1020 W Madison St',
   'address2': '',
   'address3': '',
   'city': 'Chicago',
   'zip_code': '60607',
   'country': 'US',
   'state': 'IL',
   'display_address': ['1020 W Madison St', 'Chicago, IL 60607']},
  'phone': '+13128883041',
  'display_phone': '(312) 888-3041',
  'distance': 3313.005604959832},
 {'id': '0ucCbCekcn5XdzvRXnHl2w',
  'alias': 'desert-hawk-chicago',
  'name': 'Desert Hawk',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/Wvt0tJNb-HbxRnBQ7iUUPQ/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/desert-hawk-chicago?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 45,
  'categories': [{'alias': 'tradamerican', 'title': 'American'},
   {'alias': 'bars', 'title': 'Bars'}],
  'rating': 4.6,
  'coordinates': {'latitude': 41.90288666670101,
   'longitude': -87.67917606979607},
  'transactions': [],
  'location': {'address1': '2049 W Division St',
   'address2': '',
   'address3': None,
   'city': 'Chicago',
   'zip_code': '60622',
   'country': 'US',
   'state': 'IL',
   'display_address': ['2049 W Division St', 'Chicago, IL 60622']},
  'phone': '',
  'display_phone': '',
  'distance': 289.570561434659},
 {'id': '--Yw337vTC4fLKRCaw-PLQ',
  'alias': 'xochimilco-mexican-restaurant-chicago',
  'name': 'XOchimilco Mexican Restaurant',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/5Zf_QCE-uJy1FSmnz6w-AA/o.jpg',
  'is_closed': False,

# Transformación

In [9]:
df_yelp= pd.DataFrame(data["businesses"])
display (df_yelp.head())

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance
0,qjnpkS8yZO8xcyEIy5OU9A,girl-and-the-goat-chicago,Girl & The Goat,https://s3-media0.fl.yelpcdn.com/bphoto/ya6gjD...,False,https://www.yelp.com/biz/girl-and-the-goat-chi...,10667,"[{'alias': 'newamerican', 'title': 'New Americ...",4.4,"{'latitude': 41.88419277030351, 'longitude': -...",[delivery],$$$,"{'address1': '809 W Randolph', 'address2': '',...",+13124926262,(312) 492-6262,3401.238676
1,boE4Ahsssqic7o5wQLI04w,the-purple-pig-chicago,The Purple Pig,https://s3-media0.fl.yelpcdn.com/bphoto/8993TK...,False,https://www.yelp.com/biz/the-purple-pig-chicag...,8984,"[{'alias': 'tapasmallplates', 'title': 'Tapas/...",4.3,"{'latitude': 41.890694, 'longitude': -87.624782}","[pickup, delivery]",$$$,"{'address1': '444 N Michigan Ave', 'address2':...",+13124641744,(312) 464-1744,4672.658118
2,riT822EnU7y_5eCuJsd9sA,cindys-rooftop-chicago,Cindy's Rooftop,https://s3-media0.fl.yelpcdn.com/bphoto/XLdHyZ...,False,https://www.yelp.com/biz/cindys-rooftop-chicag...,2812,"[{'alias': 'newamerican', 'title': 'New Americ...",4.1,"{'latitude': 41.8816894031196, 'longitude': -8...","[restaurant_reservation, delivery]",$$$,"{'address1': '12 S Michigan Ave', 'address2': ...",+13127923502,(312) 792-3502,5091.190048
3,PZe0q_153VHUnaR-8dOTJg,the-dearborn-chicago-2,The Dearborn,https://s3-media0.fl.yelpcdn.com/bphoto/eSXeGi...,False,https://www.yelp.com/biz/the-dearborn-chicago-...,2739,"[{'alias': 'newamerican', 'title': 'New Americ...",4.4,"{'latitude': 41.8842528, 'longitude': -87.6293...","[delivery, pickup]",$$,"{'address1': '145 N Dearborn St', 'address2': ...",+13123841242,(312) 384-1242,4637.043533
4,cgIuo3geaxw1Sfhbqm5qTA,alla-vita-chicago-4,Alla Vita,https://s3-media0.fl.yelpcdn.com/bphoto/X4XMxK...,False,https://www.yelp.com/biz/alla-vita-chicago-4?a...,813,"[{'alias': 'italian', 'title': 'Italian'}]",4.4,"{'latitude': 41.88468, 'longitude': -87.642322}","[delivery, pickup]",$$$,"{'address1': '564 W Randolph St', 'address2': ...",+13126670104,(312) 667-0104,3714.575091

In [10]:
contador= 0
lista_consolidada= []
while contador < 200:
    params={'term':'restaurants','location': ciudad,'limit':50,'offset':contador}
    response=requests.get(api_url,params=params,headers=headers)
    if response.status_code != 200:  
        break   
    
    data=response.json()
    

    df_yelp = pd.json_normalize(
        data['businesses'],
        record_path='categories',
        meta=[
            'id', 'name', 'review_count', 'rating', 'price',
            ['coordinates', 'latitude'],
            ['coordinates', 'longitude'],
            ['location', 'address1']
        ],
        sep='_',
        errors='ignore'
    )
    lista_consolidada.append(df_yelp)
    contador += 50

In [11]:
df_api_yelp_v2= pd.concat(lista_consolidada, ignore_index=True)
display(df_api_yelp_v2.head())

,alias,title,id,name,review_count,rating,price,coordinates_latitude,coordinates_longitude,location_address1
0,newamerican,New American,qjnpkS8yZO8xcyEIy5OU9A,Girl & The Goat,10667,4.4,$$$,41.884193,-87.647946,809 W Randolph
1,bars,Bars,qjnpkS8yZO8xcyEIy5OU9A,Girl & The Goat,10667,4.4,$$$,41.884193,-87.647946,809 W Randolph
2,bakeries,Bakeries,qjnpkS8yZO8xcyEIy5OU9A,Girl & The Goat,10667,4.4,$$$,41.884193,-87.647946,809 W Randolph
3,tapasmallplates,Tapas/Small Plates,boE4Ahsssqic7o5wQLI04w,The Purple Pig,8984,4.3,$$$,41.890694,-87.624782,444 N Michigan Ave
4,mediterranean,Mediterranean,boE4Ahsssqic7o5wQLI04w,The Purple Pig,8984,4.3,$$$,41.890694,-87.624782,444 N Michigan Ave

In [28]:
print(f"el número de restaurantes obtenidos es: {len(df_yelp)}")
print(f"el número de restaurantes obtenidos es: {len(df_api_yelp_v2)}")

el número de restaurantes obtenidos es: 117
el número de restaurantes obtenidos es: 457

In [22]:
#Queremos saber cuántas categorías unicas de restaurantes hay
print(df_api_yelp_v2["title"].unique())

['New American' 'Bars' 'Bakeries' 'Tapas/Small Plates' 'Mediterranean'
 'Seafood' 'Breakfast & Brunch' 'Beer, Wine & Spirits' 'Italian'
 'Wine Bars' 'Steakhouses' 'Cocktail Bars' 'Speakeasies' 'Salad'
 'American' 'Breweries' 'Thai' 'Burgers' 'Desserts' 'Mexican'
 'Venues & Event Spaces' 'Dim Sum' 'Barbeque' 'Coffee & Tea' 'Peruvian'
 'Korean' 'Japanese' 'Asian Fusion' 'Noodles' 'Latin American' 'Caribbean'
 'Pasta Shops' 'Filipino' 'Modern European' 'Beer Bar' 'Ramen' 'Izakaya'
 'Turkish' 'Restaurants' 'Sandwiches' 'Brasseries' 'Cooking Classes'
 'Pizza' 'Delis' 'Southern' 'Tex-Mex' 'Pubs' 'British' 'Sushi Bars'
 'Specialty Food' 'Poke' 'Indian' 'Soul Food' 'Comfort Food' 'Lebanese'
 'Falafel' 'French' 'Vegetarian' 'Vegan' 'Tacos' 'Middle Eastern'
 'Brewpubs' 'Chinese' 'Shanghainese' 'Szechuan' 'Cambodian' 'Food Court'
 'Soup' 'Cafes' 'Argentine' 'Hawaiian' 'Sardinian' 'Chicken Wings'
 'Spanish' 'Vietnamese' 'Hainan' 'Karaoke' 'African' 'Somali' 'Halal'
 'Greek' 'Caterers' 'Food Delivery Services' 'Pop-Up Restaurants'
 'Cajun/Creole' 'Fish & Chips' 'Himalayan/Nepalese' 'Laotian' 'Malaysian'
 'Singaporean' 'Supper Clubs' 'Ukrainian' 'Puerto Rican' 'Cuban'
 'Chicken Shop' 'Japanese Curry' 'Diners' 'Lounges' 'Venezuelan'
 'Georgian' 'Sports Bars']

In [ ]:
mapeo = {
    # Vegetariano/Vegano
    'Salad': 'Vegetariano/Vegano',

    # Mariscos/Pescado
    'Seafood': 'Mariscos/Pescado',
    'Ramen': 'Mariscos/Pescado',
    'Izakaya': 'Mariscos/Pescado',
    'Japanese': 'Mariscos/Pescado',
    'Noodles': 'Mariscos/Pescado',

    # Carnes
    'Steakhouses': 'Carnes',
    'Burgers': 'Carnes',
    'American': 'Carnes',
    'New American': 'Carnes',
    'Latin American': 'Carnes',
    'Mexican': 'Carnes',
    'Tacos': 'Carnes',
    'Caribbean': 'Carnes',
    'Delis': 'Carnes',
    'Sandwiches': 'Carnes',
    'Indian': 'Carnes',
    'Peruvian': 'Carnes',
    'Filipino': 'Carnes',
    'Korean': 'Carnes',
    'Turkish': 'Carnes',

    # Otro
    'Bars': 'Otro',
    'Bakeries': 'Otro',
    'Breakfast & Brunch': 'Otro',
    'Tapas/Small Plates': 'Otro',
    'Mediterranean': 'Otro',
    'Cocktail Bars': 'Otro',
    'Speakeasies': 'Otro',
    'Beer, Wine & Spirits': 'Otro',
    'Italian': 'Otro',
    'Wine Bars': 'Otro',
    'Thai': 'Otro',
    'Breweries': 'Otro',
    'Venues & Event Spaces': 'Otro',
    'Pubs': 'Otro',
    'Pasta Shops': 'Otro',
    'Asian Fusion': 'Otro',
    'Beer Bar': 'Otro',
    'Pizza': 'Otro',
    'Modern European': 'Otro',
    'Karaoke': 'Otro',
    'Restaurants': 'Otro'
}

#Crear columna nueva estandarizada
df_api_yelp_v2["categoria_estandarizada"] = df_api_yelp_v2["title"].map(mapeo).fillna("Otro")

print(df_api_yelp_v2["categoria_estandarizada"].value_counts())

categoria_estandarizada
Otro                  303
Carnes                119
Mariscos/Pescado       30
Vegetariano/Vegano      5
Name: count, dtype: int64

In [15]:
mapeo.update({
    # Carnes
    'Breakfast & Brunch': 'Carnes',
    'Pasta Shops': 'Carnes',
    'Tapas/Small Plates': 'Carnes',
    'Pizza': 'Vegetariano/Vegano',
    'Italian': 'Vegetariano/Vegano',

    # Vegetariano/Vegano
    'Mediterranean': 'Vegetariano/Vegano',
    'Asian Fusion': 'Vegetariano/Vegano',
    'Thai': 'Vegetariano/Vegano',
    
})

df_api_yelp_v2["categoria_estandarizada"] = df_api_yelp_v2["title"].map(mapeo).fillna("Otro")

print(df_api_yelp_v2["categoria_estandarizada"].value_counts())

categoria_estandarizada
Otro                  213
Carnes                147
Vegetariano/Vegano     67
Mariscos/Pescado       30
Name: count, dtype: int64

In [16]:
print("Rating promedio:", df_api_yelp_v2["rating"].mean())
print("Reseñas promedio:", df_api_yelp_v2["review_count"].mean())
print("Mínimo reseñas:", df_api_yelp_v2["review_count"].min())
print("Máximo reseñas:", df_api_yelp_v2["review_count"].max())

Rating promedio: 4.373085339168486
Reseñas promedio: 687.6695842450766
Mínimo reseñas: 4
Máximo reseñas: 10667

### Hacemos una ponderación del rating para poder hacer recomendaciones a los usuarios

In [17]:
#(peso de penalización — entre más lejos esté un restaurante de 500 reseñas, más se acerca su rating ponderado 
# al promedio general)

C = df_api_yelp_v2["rating"].mean()
m = 500

v = df_api_yelp_v2["review_count"]
R = df_api_yelp_v2["rating"]

df_api_yelp_v2["rating_ponderado"] = (v / (v + m)) * R + (m / (v + m)) * C
df_api_yelp_v2[["name", "rating", "review_count", "rating_ponderado"]].sort_values("rating_ponderado", ascending=False).head(10)

                              name rating review_count rating_ponderado
16                        Penumbra    4.8         1029         4.660394
15                        Penumbra    4.8         1029         4.660394
14                        Penumbra    4.8         1029         4.660394
164                   Cedar Palace    4.8          531         4.592961
163                   Cedar Palace    4.8          531         4.592961
13                      Ciccio Mio    4.7          632         4.555603
45   XOchimilco Mexican Restaurant    4.8          358         4.551215
60                           Amaru    4.7          479         4.533036
61                           Amaru    4.7          479         4.533036
62                           Amaru    4.7          479         4.533036

In [18]:
top3_por_categoria= (
    df_api_yelp_v2.sort_values("rating_ponderado", ascending=False)
    .drop_duplicates(subset="name")
    .groupby("categoria_estandarizada").head(3)
    [["name", "categoria_estandarizada", "rating", "review_count", "rating_ponderado", "location_address1"]]
    .sort_values(["categoria_estandarizada","rating_ponderado"],ascending=[True,False])
)
display(top3_por_categoria)

,name,categoria_estandarizada,rating,review_count,rating_ponderado,location_address1
16,Penumbra,Carnes,4.8,1029,4.660394,3309 W Fullerton Ave
45,XOchimilco Mexican Restaurant,Carnes,4.8,358,4.551215,2030-32 W Montrose Ave
60,Amaru,Carnes,4.7,479,4.533036,1904 W North Ave
28,Bavette's Bar & Boeuf,Mariscos/Pescado,4.5,3501,4.48414,218 W Kinzie
425,Chef’s Special Cocktail Bar,Mariscos/Pescado,4.4,348,4.384131,2165 N Western Ave
292,Sho,Mariscos/Pescado,4.9,10,4.383417,1533 N Wells St
164,Cedar Palace,Otro,4.8,531,4.592961,655 W Armitage Ave
417,Bolivar & Lincoln Venezuelan Cafe,Otro,4.8,289,4.529458,3349 N Sheffield Ave
162,The Soul Food Lounge,Otro,4.6,438,4.479043,3804 W 16th St
13,Ciccio Mio,Vegetariano/Vegano,4.7,632,4.555603,226 W Kinzie
220,La Nonna,Vegetariano/Vegano,4.7,439,4.525924,3400 N Lawndale Ave
151,En Hakkore 2.0,Vegetariano/Vegano,4.6,622,4.498879,1467 N Milwaukee Ave

## Cierre de avance 2
Se exporta el df_api_yelp_2 listo para continuar con su análisis en el avance_2
donde se integrara con datos del df_chicago para hacer recomendaciones de restaurantes

In [19]:
df_api_yelp_v2.to_csv ("df_api_yelp_limpio.csv",index=False)
print("df_api_yelp_limpio.csv exportado correctamente")

df_api_yelp_limpio.csv exportado correctamente